name: ci-test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services: 
      - name: PostgreSQL
        image: postgres:17
        env:
          POSTGRES_USER: alphaogilo
          POSTGRES_PASSWORD: Pass123456
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25.1
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
      
      - name: Run migrations
        run: make migrateup

      - name: Run tests
        run: make test