name: ci-test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25.1
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: make test